### PR TITLE
Add github action to run a test

### PR DESCRIPTION
**Pull request by Cjen1**

### CODE REVIEW

**Comment by heidihoward** [comment]
@Cjen1 were you able to fix this?

**Comment by Cjen1** [comment]
@heidihoward unfortunately not, I can't find any documentation on this nor what the specific might be... (that being said seemingly travis works on the mininet repo so going to try that...)

**Comment by heidihoward** [comment]
Do you get the same error when you run the same sequence of commands on a clean VM with the same OS, same libraries etc?

**Comment by Cjen1** [comment]
Don't know, need to spin up a VM for that... There doesn't seem to be any inherent issue running mininet on github actions.

(https://github.com/Cjen1/Resolving-Consensus/pull/11/checks?check_run_id=1402627315 is failing at the same place that it does on their master branch running under travis ci)

**Comment by heidihoward** [comment]
I think you'll have a much easier time debugging this if you can reproduce the error locally where you can interact directly with the system.

**Comment by Cjen1** [comment]
Yep got a VM spun up and  had it building for the past hour or so. Will post the results here.

**Comment by Cjen1** [comment]
Ran out of space in the VM... rebuilding with more allocated...

**Comment by Cjen1** [comment]
Getting same issue in VM. Can look into it more tomorrow.

**Comment by heidihoward** [comment]
How much disk space are you allocating to the VM? 50GB should give you plenty of space

**Comment by Cjen1** [comment]
Its up at 50GB now, with the test running, having the same issue @seveneng was having last week with the test starting, but not running fully, which the client is reporting as being the fault of the pipe disconnecting.

**Pull request merged**
